### ISSUE TITLE
请问nacos中的配置在哪获取

### ISSUE THREAD

**Issue by CaoUncle** [yangzongzhuan/RuoYi-Cloud#12]
请问nacos中的配置在哪获取

**Comment by relidaning** [comment]
有个库ry-config, 其中有个表config_info， 是说的那些配置么

**Comment by yangzongzhuan** [comment]
https://github.com/yangzongzhuan/RuoYi-Cloud/tree/master/sql  里面有ry-config_xxxx.sql
