### ISSUE TITLE
如何实现灰度发布功能？如何修改负载均衡规则？

### ISSUE THREAD

**Issue by zhunahao** [yangzongzhuan/RuoYi-Cloud#13]
文档中说负载均衡使用的是`Ribbon`，但在项目中并没有找到`Ribbon`相关的依赖包。

**Comment by yangzongzhuan** [comment]
最新的版本没有Ribbon

**Comment by ChengJun24** [comment]
nginx和后台都做集群，发布后台的时候，先改nginx负载到运行正常的后台，待后台发布结束后，一个个nginx改回负载到最新的后台上。
