### ISSUE TITLE
可直接通过各个服务的端口访问

### ISSUE THREAD

**Issue by koji0709** [yangzongzhuan/RuoYi-Cloud#16]
目前发现可绕过网关，可直接通过各个服务的端口访问，请问这一块鉴权该怎么实现呢

**Comment by Veivy** [comment]
发布到服务器后只开放网关的端口，其他微服务的端口是不对外开放的。所以只能通过网关去访问

**Comment by yangzongzhuan** [comment]
是的，通过网关访问，而不是开放其他服务对外。

**Comment by ChengJun24** [comment]
> 



> 目前发现可绕过网关，可直接通过各个服务的端口访问，请问这一块鉴权该怎么实现呢

答：可以在各个服务加拦截器，然后在网关配置自定义参数，从各个服务的拦截器拿这个参数，校验参数，校验失败就给走网关的提示。当然一般在生产环境不会开各个服务的端口的，所以生产环境不用担心这个问题。
