### ISSUE TITLE
this.$tab.openPage("用户管理", "/system/user");

### ISSUE THREAD

**Issue by Luckbaby** [yangzongzhuan/RuoYi-Cloud#17]
请问this.$tab.openPage,如何传参给打开的页面

**Comment by yangzongzhuan** [comment]
:ok_hand:  已经支持。
[添加页签openPage支持传递参数](https://gitee.com/y_project/RuoYi-Cloud/commit/f7b761275c98e34ce6f7a76c1763c2603db650f3)
`https://gitee.com/y_project/RuoYi-Cloud/commit/f7b761275c98e34ce6f7a76c1763c2603db650f3`
