### ISSUE TITLE
springdoc-openapi

### ISSUE THREAD

**Issue by vwyuheng** [yangzongzhuan/RuoYi-Cloud#19]
建议将springfox迁移到springdoc-openapi

**Comment by yangzongzhuan** [comment]
暂时没有计划，有需要可以自己先进行更换。
欢迎整合好后可以提供出地址，我给加入到项目扩展 http://doc.ruoyi.vip/ruoyi-cloud/document/xmkz.html 方便更多小伙伴看到学习，
