### ISSUE TITLE
mybatis-plus与lombok

### ISSUE THREAD

**Issue by Zard1967** [yangzongzhuan/RuoYi-Cloud#25]
项目作者, 你好:
        项目新版本是否考虑, 集成mybatis-plus与lombok, 这样可以简化代码、方便开发.
谢谢!

**Comment by yangzongzhuan** [comment]
目前不考虑，有需要可以参考项目扩展集成一下 http://doc.ruoyi.vip/ruoyi-cloud/document/xmkz.html
