### ISSUE TITLE
连接的是阿里云服务器上部署的MySQL数据库，结果每次运行项目后没操作一小会，就开始报一些警告

### ISSUE THREAD

**Issue by zzpbegin** [yangzongzhuan/RuoYi-Cloud#29]
一、问题描述
连接的是阿里云服务器上部署的MySQL数据库，结果每次运行项目后没操作一小会，就开始报一些警告，具体如下：
​ The last packet successfully received from the server was 1,209,470 milliseconds ago. The last packet sent successfully to the server was 5,005 milliseconds ago.). Possibly consider using a shorter maxLifetime value.

然后连接就断开，无法访问数据库了。

二、原因分析
​ 上面的问题总而言之意思就是，连接存活时间超时了之类的，但是数据库中的设置和我的连接池设置的空闲存活时间跟最大存活时间都远大于空闲时间，所以按理说不应该出现这种情况，而换到我本地的数据库，配置完全相同也不会出现这种情况，根据网上说的一些方法修改也不成功。
​ 再查了查，发现应该是因为云服务器的Linux系统上的安全设置问题，如果在一段时间内没有与服务器进行交互就会断开连接，包括在用ssh连接云服务器时，如果一段时间不操作，也会卡死只能重连，所以只要是在本地的，就不会出现这种情况。

目前没找到解决办法！！！

**Comment by ChengJun24** [comment]
是的，阿里云服务器默认会有远程连接时间限制，大约五分钟不操作就会掉线，可以更改阿里云服务器安全组的相关配置解决此问题，和你本地的代码没关系。

**Comment by yangzongzhuan** [comment]
微服务版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Cloud/issues 需要提供出能复现问题详细步骤。
