### ISSUE TITLE
请问下大家 RuoYi-Vue3 里面是 Vue3，能直接结合 RuoYi-Cloud 里的后台直接用 吗？

### ISSUE THREAD

**Issue by delbug** [yangzongzhuan/RuoYi-Cloud#32]
请问下大家 RuoYi-Vue3 里面是 Vue3，能直接结合 RuoYi-Cloud 里的后台直接用 吗？

![image](https://user-images.githubusercontent.com/47682158/220818443-42fa46d1-4eac-41bd-bc2a-425f6220099f.png)

**Comment by boot-vue** [comment]
cloud对应这个    https://github.com/yangzongzhuan/RuoYi-Cloud-Vue3

**Comment by yangzongzhuan** [comment]
微服务版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Cloud/issues
