### ISSUE TITLE
RuoYiSystemApplication 启动失败

### ISSUE THREAD

**Issue by ChenLivew** [yangzongzhuan/RuoYi-Cloud#37]
RuoYiSystemApplication 启动失败

**Comment by czgggggggg** [comment]
同样的问题
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sysConfigController': Unsatisfied dependency expressed through field 'configService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sysConfigServiceImpl': Invocation of init method failed; nested exception is org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.ruoyi.system.mapper.SysConfigMapper.selectConfigList

**Comment by 54wangrq** [comment]
这个可以关闭的
我今天也出现 org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): com.ruoyi.system.mapper.SysConfigMapper.selectConfigList
实际是本地配置环境问题，配置的nacos未读到数据，直接将配置写到boostrap.yml 则启动成功，后续调整nacos配置则ok

**Comment by yangzongzhuan** [comment]
微服务版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Cloud/issues 需要提供出能复现问题详细步骤。

**Comment by CodingMan-ops** [comment]
在本地boostrap.yml写配置文件，报错com/hdsxtech/system/api/domain/SysDept (wrong name: com/hdsxtech/system/api/domain/sysDept)
