### ISSUE TITLE
登录接口/auth/login不存在

### ISSUE THREAD

**Issue by HEEKDragonOne** [yangzongzhuan/RuoYi-Cloud#38]
登录接口不存在，和前端发送的请求不一致
![image](https://github.com/yangzongzhuan/RuoYi-Cloud/assets/63946632/c504d92e-db92-4f53-adf1-a2dd9a98508d)

![image](https://github.com/yangzongzhuan/RuoYi-Cloud/assets/63946632/c91c15b3-e53e-4645-911c-4501e8dd4175)

**Comment by HEEKDragonOne** [comment]
已解决

**Comment by yangzongzhuan** [comment]
微服务版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Cloud/issues
