### ISSUE TITLE
鉴权方式为什么不采用网关统一鉴权而是硬编码方式鉴权

### ISSUE THREAD

**Issue by MainPoser** [yangzongzhuan/RuoYi-Cloud#4]
1、代码中auth服务负责用户认证，颁发token。
2、网关服务负责转发请求，
3、各个模块负责用户权限鉴权，且是硬编码方式（个人认为及其不合理，应当为数据库配置权限信息，动态鉴权）
问：为什么不在网关做统一动态鉴权？，所有服务入口通过网关进行转发。

**Comment by atliwen** [comment]
我也是找个问题，硬编码方式 关系还是API地址与用户角色权限匹配。完全可以放在 网关层做统一鉴权啊。

**Comment by MainPoser** [comment]
根据他们的回复
1、性能问题，但是我觉得可以集群化部署网关解决
2、相关模块名称产生变化导致访问路径变化，鉴权失败的问题。但是我觉得一个微服务的名称定下来一般不会动了。
