### ISSUE TITLE
ruoyi-ui在MAC系统上安装，依赖包一堆冲突

### ISSUE THREAD

**Issue by ricklui919** [yangzongzhuan/RuoYi-Cloud#43]
主要是webpack版本不知道选哪个，按配置依赖设定的版本，compression-webpack-plugin要求webpack 5.1.0以上，但其他很多组件要求低，无法同时满足

**Comment by yangzongzhuan** [comment]
微服务版本问题请到这里提问 https://gitee.com/y_project/RuoYi-Cloud/issues
