### ISSUE TITLE
菜单或者目录路径命名重复导致vue-router路由出现404问题

### ISSUE THREAD

**Issue by pei-han** [yangzongzhuan/RuoYi-Cloud#49]
菜单或者目录路径命名重复，直接导致路由name重复，在代码中使用了named route情况下，这种重复导致后面的相同name的路由覆盖之前的路由，最终出现出现404问题（菜单路径重复）
还会导致点击目录展开错误问题（目录路径重复）

**Comment by yangzongzhuan** [comment]
这个主要是发生在vue3版本中，因为vue3-router不支持重名，所以在Cloud新版本新增了路由名称，可以在菜单管理自定义路由名称。
