### ISSUE TITLE
数据库更新问题

### ISSUE THREAD

**Issue by alixiaodi** [yangzongzhuan/RuoYi-Cloud#52]
### 问题
在开发环境修改数据库字段，或者添加一个新表，在部署生产环境的时候，需要自己将创建的表和字段同步上去
### 建议
集成一种组件，可以将更新表机构的sql写入至项目中，在项目启动时，会自动检测数据库版本和修改的版本，自动完成数据库表结构的更新

**Comment by alixiaodi** [comment]
@yangzongzhuan

**Comment by BingChunMoLi** [comment]
flyway

**Comment by yangzongzhuan** [comment]
这个不考虑，因为不一定都需要，可以自己集成flyway
