### ISSUE TITLE
微服务版后台手册这个文档的格式没对齐

### ISSUE THREAD

**Issue by Eshy-C** [yangzongzhuan/RuoYi-Cloud#53]
![1725596681472](https://github.com/user-attachments/assets/84448dba-8c0d-4858-bcdd-72c70cb1f194)

**Comment by yangzongzhuan** [comment]
我这里看没有问题哦 
![image](https://github.com/user-attachments/assets/7a3c0801-1876-43ee-adc0-0c03723aef95)

**Comment by Eshy-C** [comment]
好像确实正常了
