### ISSUE TITLE
当连不上minio时，临时文件会被一直占用，这块有问题

### ISSUE THREAD

**Issue by cherry-min** [yangzongzhuan/RuoYi-Cloud#61]
![image](https://github.com/user-attachments/assets/db6169e7-0547-4f2f-b994-7440b340cf82)

**Comment by cherry-min** [comment]
![image](https://github.com/user-attachments/assets/f6a6a6a7-4a94-4678-a37a-6c6f28a1557a)

**Comment by yangzongzhuan** [comment]
嗯，多谢提醒。已经修复 [优化文件异常输入流未关闭的问题](https://github.com/yangzongzhuan/RuoYi-Cloud/commit/92c6d218554b028a8085514eeb18f1dfcd41af58)`https://github.com/yangzongzhuan/RuoYi-Cloud/commit/92c6d218554b028a8085514eeb18f1dfcd41af58`
