### ISSUE TITLE
mybitis: typeAliasesPackage

### ISSUE THREAD

**Issue by baoxu2017** [yangzongzhuan/RuoYi-Cloud#7]
typeAliasesPackage: com.ruoyi.system
typeAliasesPackage: com.ruoyi.gen.domain

问题：实体类都在xxx.domain下，为什么system不需要，加上反而报错，没有看到其他地方有配置，求解惑

**Comment by yangzongzhuan** [comment]
不配置默认就是扫描当前包及以下。这是mybatis的特性 框架没有任何处理。
