### ISSUE TITLE
maven install 失败了,咋整??

### ISSUE THREAD

**Issue by ithjz** [yangzongzhuan/RuoYi-Cloud#8]
Could not transfer artifact org.springframework.cloud:spring-cloud-dependencies:pom:Hoxton.SR9 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-dependencies/Hoxton.SR9/spring-cloud-dependencies-Hoxton.SR9.pom

**Comment by yangzongzhuan** [comment]
多尝试几次，或者更换maven源
